import type { ResearchStore } from "./model";

export const demoStore: ResearchStore = {
  version: 1,
  updatedAt: "2026-08-13T08:00:00.000Z",
  signals: [
    {
      id: "sig-01",
      title: "端侧算力进入消费硬件体验定义",
      summary: "对工业设计的影响不只在手机，而在散热、续航、形态、交互边界与可维修性。",
      quadrant: "技术与工具",
      ring: "试验",
      movement: "上升",
      impact: 1,
      confidence: 66,
      sourceName: "项目假设 / 待持续验证",
      observedAt: "2026-08-08",
      tags: ["端侧计算", "产品体验"],
    },
    {
      id: "sig-02",
      title: "生成式工具压缩概念表达时间",
      summary: "草图、情绪板与早期渲染被加速，但问题定义和工程闭环的重要性上升。",
      quadrant: "技术与工具",
      ring: "行动",
      movement: "稳定",
      impact: 1,
      confidence: 78,
      sourceName: "课程与工作流观察",
      observedAt: "2026-08-06",
      tags: ["生成式设计", "工作流"],
    },
    {
      id: "sig-03",
      title: "可维修与全生命周期要求增强",
      summary: "法规、企业采购与消费者信任共同提高可拆解、材料追溯和维修设计的价值。",
      quadrant: "社会与规则",
      ring: "试验",
      movement: "上升",
      impact: 2,
      confidence: 72,
      sourceName: "EU Ecodesign for Sustainable Products",
      sourceUrl: "https://commission.europa.eu/energy-climate-change-environment/standards-tools-and-labels/products-labelling-rules-and-requirements/ecodesign-sustainable-products-regulation_en",
      observedAt: "2026-08-05",
      tags: ["可持续", "维修权"],
    },
    {
      id: "sig-04",
      title: "企业从概念数量转向验证质量",
      summary: "危机前后更稀缺的不是更多效果图，而是把用户证据、成本和制造约束连起来。",
      quadrant: "需求与商业",
      ring: "研究",
      movement: "上升",
      impact: 2,
      confidence: 61,
      sourceName: "研究假设 / 访谈待补",
      observedAt: "2026-08-04",
      tags: ["设计价值", "ROI"],
    },
    {
      id: "sig-05",
      title: "小批量制造降低行业进入门槛",
      summary: "快速加工、柔性供应链和众筹验证让学生团队可以更早接触真实产品闭环。",
      quadrant: "制造与材料",
      ring: "试验",
      movement: "稳定",
      impact: 1,
      confidence: 68,
      sourceName: "制造服务案例观察",
      observedAt: "2026-08-02",
      tags: ["小批量", "供应链"],
    },
    {
      id: "sig-06",
      title: "同质化 AI 概念图降低作品集区分度",
      summary: "视觉产出变多后，研究过程、结构推演、样机验证和复盘更能区分能力。",
      quadrant: "需求与商业",
      ring: "行动",
      movement: "上升",
      impact: -1,
      confidence: 75,
      sourceName: "作品集观察 / 待量化",
      observedAt: "2026-07-29",
      tags: ["作品集", "同质化"],
    },
    {
      id: "sig-07",
      title: "生物基与再生材料从叙事走向量产约束",
      summary: "材料选择需要同时回答性能、供应稳定、模具适配和回收路径。",
      quadrant: "制造与材料",
      ring: "研究",
      movement: "稳定",
      impact: 1,
      confidence: 59,
      sourceName: "材料样本库观察",
      observedAt: "2026-07-26",
      tags: ["材料", "量产"],
    },
    {
      id: "sig-08",
      title: "AI 投资与真实利润之间的缺口需持续跟踪",
      summary: "这是 2029 泡沫假设的关键前置变量，不能由媒体热度替代财务与订单证据。",
      quadrant: "需求与商业",
      ring: "关注",
      movement: "稳定",
      impact: -2,
      confidence: 48,
      sourceName: "核心研究问题",
      observedAt: "2026-07-24",
      tags: ["AI泡沫", "资本开支"],
    },
  ],
  indicators: [
    { id: "ind-01", label: "工业设计招聘与实习", category: "需求与商业", value: 1, direction: 0, weight: 1.2, note: "看职位数量，也看岗位职责是否扩张。" },
    { id: "ind-02", label: "消费硬件新品与订单", category: "需求与商业", value: 1, direction: 1, weight: 1.1, note: "优先观察真实出货、复购和渠道库存。" },
    { id: "ind-03", label: "AI 投资/利润兑现差", category: "需求与商业", value: 0, direction: 0, weight: 1.4, note: "差距扩大为负，兑现改善为正。" },
    { id: "ind-04", label: "原型与小批量成本", category: "制造与材料", value: 1, direction: 0, weight: 0.8, note: "成本下降、交期稳定记为正向。" },
    { id: "ind-05", label: "可持续与维修规则", category: "社会与规则", value: 1, direction: 1, weight: 0.8, note: "规则明确会创造新的设计任务。" },
    { id: "ind-06", label: "设计工具自动化渗透", category: "技术与工具", value: 1, direction: 1, weight: 1, note: "关注是否替代流程节点，以及新出现的验证任务。" },
  ],
  hypotheses: [
    {
      id: "hyp-01",
      title: "H1 · AI 行业泡沫破裂",
      statement: "AI 行业可能在 2029 年左右进入明显估值与投资收缩，并冲击工业设计相关的消费硬件、创新预算与招聘。",
      timeWindow: "2028 Q2 — 2030 Q1",
      confidence: 56,
      status: "跟踪中",
      evidenceFor: ["资本开支与利润兑现差可能扩大", "工具与概念供给增速高于真实产品需求", "消费硬件创新预算对融资周期敏感"],
      evidenceAgainst: ["端侧与工业应用可能形成稳定现金流", "基础设施投资周期可能更长", "工业设计需求不与 AI 行业单向同步"],
      falsifier: "若 2028–2030 年主要 AI 产品持续实现可验证利润增长，且相关硬件招聘与订单未出现同步收缩，则降低或否定该假设。",
    },
    {
      id: "hyp-02",
      title: "H2 · 恢复窗口极短",
      statement: "破裂后的工业设计相关机会可能在 6–12 个月内重新启动，先集中于降本、改造、可靠性和真实场景产品。",
      timeWindow: "危机触发后 6–12 个月",
      confidence: 52,
      status: "待验证",
      evidenceFor: ["硬件供应链重组可快速释放新任务", "低谷期形成的低估资产与人才会被重新组合", "端侧算力和自动化仍可能保留真实需求"],
      evidenceAgainst: ["宏观需求修复可能超过一年", "企业可能先恢复软件与销售预算", "学生进入窗口受毕业时点和地域限制"],
      falsifier: "若危机后 12 个月仍未出现订单、招聘、投融资任一组连续两个季度改善，则延长恢复周期判断。",
    },
  ],
  skills: [
    { id: "sk-01", name: "问题定义与设计研究", category: "研究", level: 2, target: 4, priority: "高", evidence: "完成 2 次课程访谈与洞察整理", nextAction: "做一次 5 人小样本访谈并保留原始证据", crisisValue: "避免在需求收缩期做无效概念" },
    { id: "sk-02", name: "CMF 与材料验证", category: "工程", level: 1, target: 3, priority: "中", evidence: "有基础材料板，无量化测试", nextAction: "建立 12 种材料性能/工艺卡", crisisValue: "支持降本、替代材料与可持续改造" },
    { id: "sk-03", name: "结构与 DFM 沟通", category: "工程", level: 1, target: 3, priority: "高", evidence: "能完成基础拆件，缺少模具约束案例", nextAction: "逆向拆解一个量产小家电", crisisValue: "让设计更接近真实订单与供应链" },
    { id: "sk-04", name: "交互原型与端侧 AI 体验", category: "数字", level: 2, target: 3, priority: "中", evidence: "完成 1 个 Figma 流程原型", nextAction: "做一个离线智能硬件交互演示", crisisValue: "连接硬件形态、交互和计算限制" },
    { id: "sk-05", name: "生成式工具编排与判断", category: "数字", level: 2, target: 4, priority: "高", evidence: "能生成概念方案，缺少评估基准", nextAction: "记录 3 轮同题对照及人工修改理由", crisisValue: "保留效率，同时避免同质化" },
    { id: "sk-06", name: "成本、商业与机会评估", category: "商业", level: 1, target: 3, priority: "高", evidence: "有粗略 BOM，未做敏感性分析", nextAction: "为课程项目补齐 BOM 与三档售价", crisisValue: "把设计价值转为可决策指标" },
  ],
  opportunities: [
    { id: "opp-01", title: "可维修消费电子改造", horizon: "复苏窗口", status: "准备", trigger: "维修法规明确 + 品牌库存改造需求上升", targetUser: "中小硬件品牌", readiness: 58, timing: 66, resilience: 82, nextAction: "拆解 2 款耳机并做可维修结构对比" },
    { id: "opp-02", title: "小批量医疗/适老辅助产品", horizon: "现在", status: "验证", trigger: "真实照护场景出现高频不便", targetUser: "社区与照护机构", readiness: 62, timing: 60, resilience: 88, nextAction: "完成 3 次情境观察，确认一个高频动作" },
    { id: "opp-03", title: "端侧 AI 硬件体验定义", horizon: "复苏窗口", status: "观察", trigger: "模型能力稳定且功耗/成本显著下降", targetUser: "智能硬件团队", readiness: 42, timing: 72, resilience: 55, nextAction: "建立算力、散热、续航与交互取舍表" },
    { id: "opp-04", title: "制造端降本与替代材料设计", horizon: "危机期", status: "准备", trigger: "订单下滑但改款和降本任务增加", targetUser: "制造企业与供应商", readiness: 55, timing: 78, resilience: 90, nextAction: "用一个现有产品做 10% 成本下降推演" },
  ],
  discussions: [
    { id: "dis-01", title: "2029 是节点还是观察窗口？", category: "研究问题", body: "建议把单年预测改写为 2028 Q2–2030 Q1 的观察窗口，并设置季度触发器。", author: "Mina", createdAt: "2026-08-11", replies: 4, status: "已形成决策", decision: "系统展示 2029 核心节点，同时以 ±12 个月窗口管理不确定性。" },
    { id: "dis-02", title: "恢复期为何只有 6–12 个月", category: "反方证据", body: "需要区分 AI 投资恢复、消费硬件订单恢复和工业设计招聘恢复，三者可能不同步。", author: "研究组", createdAt: "2026-08-10", replies: 2, status: "开放" },
    { id: "dis-03", title: "把作品集改造成危机可用的能力证据", category: "行动提案", body: "每个项目增加研究原始材料、工程取舍、成本范围和失败复盘四个附录。", author: "Mina", createdAt: "2026-08-09", replies: 6, status: "开放" },
  ],
};

export const scenarioPresets = {
  baseline: {
    label: "基准准备",
    description: "需求仍在，保持储备",
    values: [1, 1, 0, 1, 1, 1],
    directions: [0, 1, 0, 0, 1, 1],
  },
  overheat: {
    label: "泡沫加速",
    description: "热度上升，兑现转弱",
    values: [0, 1, -1, 0, 1, 1],
    directions: [-1, 0, -1, 0, 0, 1],
  },
  rupture: {
    label: "断裂冲击",
    description: "预算、招聘与订单同步下滑",
    values: [-1, -1, -2, 0, 0, 1],
    directions: [-1, -1, -1, -1, 0, 0],
  },
  trough: {
    label: "低谷压缩",
    description: "压力高，仍未见拐点",
    values: [-2, -2, -2, -1, 0, 0],
    directions: [0, -1, 0, 0, 0, 0],
  },
  recovery: {
    label: "复苏窗口",
    description: "压力仍在，但先行指标回升",
    values: [-1, -1, -1, 0, 1, 1],
    directions: [1, 1, 1, 1, 1, 1],
  },
} as const;
