import type { ResearchStore } from "./model";

export const demoStore: ResearchStore = {
  version: 1,
  updatedAt: "2026-08-13T08:00:00.000Z",
  signals: [
    {
      id: "sig-01",
      title: "欧盟制造业产出是设计需求的上游信号",
      summary: "用制造业产出、订单与库存判断企业是否可能扩张新品、改款和供应链优化任务；具体方向需由最新 Eurostat 观测值校准。",
      quadrant: "需求与商业",
      ring: "行动",
      movement: "稳定",
      impact: 2,
      confidence: 72,
      sourceName: "Eurostat / 待接入最新观测",
      sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/sts_inpr_m/default/table?lang=en",
      observedAt: "2026-09-18",
      tags: ["制造业产出", "欧盟"],
    },
    {
      id: "sig-02",
      title: "实际增长决定需求总量，行业结构决定设计机会",
      summary: "GDP 只提供总量背景；必须继续拆分制造、消费、投资与企业利润，避免把宏观增长直接等同于工业设计景气。",
      quadrant: "需求与商业",
      ring: "行动",
      movement: "稳定",
      impact: 1,
      confidence: 70,
      sourceName: "Eurostat / 研究方法基线",
      sourceUrl: "https://ec.europa.eu/eurostat/databrowser/view/namq_10_gdp/default/table?lang=en",
      observedAt: "2026-09-18",
      tags: ["实际GDP", "产业结构"],
    },
    {
      id: "sig-03",
      title: "制造业就业可验证订单压力是否传到企业用工",
      summary: "就业、工时与工资应和产出共同观察；单月变化不能直接解释为长期设计岗位趋势。",
      quadrant: "需求与商业",
      ring: "试验",
      movement: "稳定",
      impact: 1,
      confidence: 68,
      sourceName: "U.S. Bureau of Labor Statistics / 待接入最新观测",
      sourceUrl: "https://data.bls.gov/timeseries/CES3000000001",
      observedAt: "2026-09-18",
      tags: ["制造业就业", "劳动力"],
    },
    {
      id: "sig-04",
      title: "通胀回落不等于材料与制造成本同步回落",
      summary: "消费价格用于判断总体价格环境，设计项目还需补充材料、能源、物流和工资等投入成本。",
      quadrant: "需求与商业",
      ring: "研究",
      movement: "稳定",
      impact: -1,
      confidence: 64,
      sourceName: "BLS / Eurostat / 待接入最新观测",
      observedAt: "2026-09-18",
      tags: ["通胀", "投入成本"],
    },
    {
      id: "sig-05",
      title: "融资条件影响高风险硬件与创新预算",
      summary: "利率与信用条件趋紧时，长周期硬件、概念验证和非核心改款更容易被延期；需结合企业现金流与资本开支核验。",
      quadrant: "需求与商业",
      ring: "研究",
      movement: "稳定",
      impact: -2,
      confidence: 62,
      sourceName: "研究框架 / 待接入利率与信用数据",
      observedAt: "2026-09-18",
      tags: ["利率", "融资条件"],
    },
    {
      id: "sig-06",
      title: "资本开支与利润共同决定创新预算承受力",
      summary: "企业资本开支上升可能带来设备与产品机会，也可能挤压其他预算；需要结合利润、现金流与行业构成判断。",
      quadrant: "需求与商业",
      ring: "研究",
      movement: "稳定",
      impact: 1,
      confidence: 60,
      sourceName: "企业披露 / 待持续收集",
      observedAt: "2026-09-18",
      tags: ["资本开支", "企业利润"],
    },
    {
      id: "sig-07",
      title: "欧盟政策文件需要区分发布页与可下载原文",
      summary: "发布页用于发现主题和附件，具体条款与技术要求必须下载 PDF 后核对，不能仅凭页面摘要形成结论。",
      quadrant: "社会与规则",
      ring: "研究",
      movement: "稳定",
      impact: 1,
      confidence: 90,
      sourceName: "European Commission publications",
      sourceUrl: "https://single-market-economy.ec.europa.eu/publications_en",
      observedAt: "2026-09-18",
      tags: ["欧盟文件", "证据边界"],
    },
    {
      id: "sig-08",
      title: "自动化提高供给效率，但需求端仍由经济条件约束",
      summary: "生成式工具可以压缩概念产出时间，是否形成更多真实设计任务仍取决于订单、投资、利润与融资环境。",
      quadrant: "技术与工具",
      ring: "关注",
      movement: "稳定",
      impact: 0,
      confidence: 58,
      sourceName: "研究假设 / 待企业数据验证",
      observedAt: "2026-09-18",
      tags: ["自动化", "需求约束"],
    },
  ],
  indicators: [
    { id: "ind-01", label: "主要市场实际增长", category: "需求与商业", value: 0, direction: 0, weight: 1.2, note: "用实际 GDP 与消费/投资分项判断需求总量，不以单季值下结论。" },
    { id: "ind-02", label: "制造业产出与订单", category: "制造与材料", value: 0, direction: 0, weight: 1.4, note: "观察产出、新订单、库存和产能利用率是否同向变化。" },
    { id: "ind-03", label: "制造业就业与工时", category: "需求与商业", value: 0, direction: 0, weight: 1.1, note: "就业和工时用于验证需求变化是否进入企业用工决策。" },
    { id: "ind-04", label: "通胀与投入成本", category: "制造与材料", value: 0, direction: 0, weight: 1, note: "通胀下降为压力缓解，但需与材料、能源、物流和工资分开判断。" },
    { id: "ind-05", label: "利率与融资条件", category: "需求与商业", value: 0, direction: 0, weight: 1.2, note: "融资越紧，长周期硬件和高风险创新预算承压越明显。" },
    { id: "ind-06", label: "企业资本开支与利润", category: "需求与商业", value: 0, direction: 0, weight: 1.3, note: "结合资本开支、利润和现金流判断企业是否具备持续创新预算。" },
  ],
  hypotheses: [
    {
      id: "hyp-01",
      title: "H1 · 经济与制造收缩会传导到设计预算",
      statement: "若实际增长、制造业产出、订单与企业利润连续走弱，工业设计相关的新品、改款、招聘和外包预算将在随后 1–3 个季度承压。",
      timeWindow: "滚动未来 4–8 个季度",
      confidence: 58,
      status: "跟踪中",
      evidenceFor: ["新品与外包预算通常依赖订单和现金流", "融资趋紧会提高长周期硬件项目门槛", "就业与工时可验证压力是否进入企业决策"],
      evidenceAgainst: ["降本、维修和替代材料任务可能逆势增加", "医疗与公共领域需求未必同步收缩", "设计预算可能由结构转型而非总量决定"],
      falsifier: "若增长、产出与利润连续两个季度走弱，而工业设计招聘、新品立项和外包订单仍连续三个季度改善，则降低或否定该传导假设。",
    },
    {
      id: "hyp-02",
      title: "H2 · 经济领先指标先于设计需求修复",
      statement: "当实际增长、制造订单、融资条件与资本开支形成连续改善后，工业设计需求可能滞后 1–3 个季度恢复，并先集中于降本、改造、可靠性和真实场景产品。",
      timeWindow: "领先指标改善后 1–3 个季度",
      confidence: 50,
      status: "待验证",
      evidenceFor: ["订单和资本开支通常先于招聘扩张", "低谷期供应链重组可能释放改造任务", "成本压力缓解可提高项目可行性"],
      evidenceAgainst: ["企业可能优先恢复销售与软件预算", "库存去化会延迟新品立项", "不同地区与行业的周期可能明显错位"],
      falsifier: "若领先指标连续两个季度改善后，设计招聘、新品立项与外包订单在三个季度内均无改善，则延长或取消恢复滞后判断。",
    },
  ],
  skills: [
    { id: "sk-01", name: "问题定义与设计研究", category: "研究", level: 2, target: 4, priority: "高", evidence: "完成 2 次课程访谈与洞察整理", nextAction: "做一次 5 人小样本访谈并保留原始证据", crisisValue: "避免在需求收缩期做无效概念" },
    { id: "sk-02", name: "CMF 与材料验证", category: "工程", level: 1, target: 3, priority: "中", evidence: "有基础材料板，无量化测试", nextAction: "建立 12 种材料性能/工艺卡", crisisValue: "支持降本、替代材料与可持续改造" },
    { id: "sk-03", name: "结构与 DFM 沟通", category: "工程", level: 1, target: 3, priority: "高", evidence: "能完成基础拆件，缺少模具约束案例", nextAction: "逆向拆解一个量产小家电", crisisValue: "让设计更接近真实订单与供应链" },
    { id: "sk-04", name: "交互原型与端侧 AI 体验", category: "数字", level: 2, target: 3, priority: "中", evidence: "完成 1 个 Figma 流程原型", nextAction: "做一个离线智能硬件交互演示", crisisValue: "连接硬件形态、交互和计算限制" },
    { id: "sk-05", name: "生成式工具编排与判断", category: "数字", level: 2, target: 4, priority: "高", evidence: "能生成概念方案，缺少评估基准", nextAction: "记录 3 轮同题对照及人工修改理由", crisisValue: "保留效率，同时避免同质化" },
    { id: "sk-06", name: "经济数据与商业判断", category: "商业", level: 1, target: 3, priority: "高", evidence: "能读单项指标，缺少跨指标与传导分析", nextAction: "每月完成一次增长、产出、就业、价格与融资的联读", crisisValue: "把宏观变化转成设计预算、成本与机会判断" },
  ],
  opportunities: [
    { id: "opp-01", title: "可维修消费电子改造", horizon: "复苏窗口", status: "准备", trigger: "维修法规明确 + 品牌库存改造需求上升", targetUser: "中小硬件品牌", readiness: 58, timing: 66, resilience: 82, nextAction: "拆解 2 款耳机并做可维修结构对比" },
    { id: "opp-02", title: "小批量医疗/适老辅助产品", horizon: "现在", status: "验证", trigger: "真实照护场景出现高频不便", targetUser: "社区与照护机构", readiness: 62, timing: 60, resilience: 88, nextAction: "完成 3 次情境观察，确认一个高频动作" },
    { id: "opp-03", title: "端侧 AI 硬件体验定义", horizon: "复苏窗口", status: "观察", trigger: "模型能力稳定且功耗/成本显著下降", targetUser: "智能硬件团队", readiness: 42, timing: 72, resilience: 55, nextAction: "建立算力、散热、续航与交互取舍表" },
    { id: "opp-04", title: "制造端降本与替代材料设计", horizon: "危机期", status: "准备", trigger: "订单下滑但改款和降本任务增加", targetUser: "制造企业与供应商", readiness: 55, timing: 78, resilience: 90, nextAction: "用一个现有产品做 10% 成本下降推演" },
  ],
  discussions: [
    { id: "dis-01", title: "从单一年份转为滚动经济观察窗", category: "研究问题", body: "单点年份无法表达周期不确定性，建议每月更新数据、每季度复核未来 4–8 个季度的压力与机会。", author: "Mina", createdAt: "2026-09-18", replies: 4, status: "已形成决策", decision: "经济数据作为上游主线，不再把 2029 作为固定结论。" },
    { id: "dis-02", title: "经济修复与设计需求可能不同步", category: "反方证据", body: "需要区分制造订单、资本开支、新品立项和工业设计招聘，验证它们之间的真实滞后。", author: "研究组", createdAt: "2026-09-18", replies: 2, status: "开放" },
    { id: "dis-03", title: "把作品集改造成危机可用的能力证据", category: "行动提案", body: "每个项目增加研究原始材料、工程取舍、成本范围和失败复盘四个附录。", author: "Mina", createdAt: "2026-08-09", replies: 6, status: "开放" },
  ],
};

export const scenarioPresets = {
  baseline: {
    label: "温和增长",
    description: "增长平稳，制造需求分化",
    values: [1, 1, 0, 0, 0, 1],
    directions: [0, 1, 0, 0, 0, 1],
  },
  overheat: {
    label: "高通胀扩张",
    description: "需求强但成本与利率上升",
    values: [2, 2, 1, -2, -1, 1],
    directions: [1, 1, 1, -1, -1, 1],
  },
  rupture: {
    label: "衰退冲击",
    description: "增长、产出、就业与利润同步走弱",
    values: [-2, -2, -1, 0, -1, -2],
    directions: [-1, -1, -1, 0, -1, -1],
  },
  trough: {
    label: "低谷去库存",
    description: "价格缓和，但订单和投资仍弱",
    values: [-1, -2, -1, 1, 0, -2],
    directions: [0, 0, 0, 1, 1, 0],
  },
  recovery: {
    label: "早期复苏",
    description: "增长、订单、融资与投资先行改善",
    values: [1, 1, 0, 1, 1, 1],
    directions: [1, 1, 1, 1, 1, 1],
  },
} as const;
